matrix:
  include:
    - language: clojure
      jdk:
        - oraclejdk8
      before_script:
        - cd front
      script:
        - lein cljsbuild once min

    - language: rust
      rust:
        - nightly
      before_script:
        - cd backend
      script:
        - cargo build
