matrix:
  include:
    - language: clojure
      jdk: oraclejdk8
      before_install: cd front
      script: lein cljsbuild once min

    - language: rust
      rust: nightly
      before_install: cd backend
      script: cargo build
      deploy:
        - provider: script
          script: bash ~/travis/deploy.sh
          on:
            all_branches: true
            #branch: master
