version: '3'
services:
  db:
    image: 'postgres:11.2'
    volumes:
      - '../db/init:/docker-entrypoint-initdb.d:ro'
      - '../run/db-data:/var/lib/postgresql/data'
    ports: [ '127.0.0.1:5432:5432' ]
    network_mode: 'host'
  nginx:
    image: 'nginx'
    volumes:
      - '../run/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '../front-elm/static:/srv/elm:ro'
      - '../front/resources/public:/srv/clj:ro'
    ports: [ '127.0.0.1:8000:8000' ]
    network_mode: 'host'
